<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df2b0e6a-bf9d-4161-a0f4-96ff3de649eb</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_131</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[9]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>