<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0d8108b2-d0b6-4d5e-922c-d14f8429858c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_66</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[3]/nav[1]/div[1]/ul[1]/a[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Edit organization information and manage security.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Edit organization information and manage security.</value>
        <webElementGuid>195f62e5-63f8-43a0-834e-e8d29a358227</webElementGuid>
    </webElementProperties>
</WebElementEntity>