<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>10932433-d338-436c-bbd3-e1ee07d00c76</elementGuidId>
    <imagePath></imagePath>
    <name>button_runTest</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>["[role=\"group\"]:nth-child(2) &gt; [class=\"btn\\ btn-secondary\"]"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Run')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=button[name=\"Run\"i]", "#main-header-tool-bar &gt;&gt; internal:role=button &gt;&gt; nth=1", "internal:role=toolbar &gt;&gt; internal:role=button &gt;&gt; nth=1"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Run</value>
        <webElementGuid>49df00f5-fabd-4a32-9675-4eb3ae5fa15f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>49df00f5-fabd-4a32-9675-4eb3ae5fa15f</webElementGuid>
    </webElementProperties>
</WebElementEntity>