<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2c379f75-32f6-4be8-bab1-04b1a949ac0e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_32</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[3]/nav[1]/div[1]/ul[1]/a[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'分配和监控 Katalon Studio。')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>分配和监控 Katalon Studio。</value>
        <webElementGuid>5f59d5b8-70da-4ae5-a7a8-e5aa1c410468</webElementGuid>
    </webElementProperties>
</WebElementEntity>