<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae79d49a-ef26-4a95-9636-99cc5ffefe37</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_120</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Update billing information.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Update billing information.</value>
        <webElementGuid>9c088bdc-3380-4ebd-829c-8a5effac63b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>