<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cb54df84-5c6e-4539-ac49-d1cc3d352359</elementGuidId>
    <imagePath></imagePath>
    <name>path_object_30</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/svg[1]/g[1]/path[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>