<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>40e03f02-09e8-4522-907b-829f7b83597a</elementGuidId>
    <imagePath></imagePath>
    <name>link_testCloudTunnels</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sub-navbar"] &gt; [class="nav-item"]:nth-child(${link_testCloudTunnels_nthChild}) &gt; [class="nav-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'TestCloud Tunnels') and equals(@href,'/team/1546818/project/1566250/testCloudTunnel') and equals(@text,'TestCloud Tunnels')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_testCloudTunnels_internalRoleLinkName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/1546818/project/1566250/testCloudTunnel</value>
        <webElementGuid>e525c793-010e-4678-b447-40d1db3dbd08</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TestCloud Tunnels</value>
        <webElementGuid>e525c793-010e-4678-b447-40d1db3dbd08</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>TestCloud Tunnels</value>
        <webElementGuid>e525c793-010e-4678-b447-40d1db3dbd08</webElementGuid>
    </webElementProperties>
</WebElementEntity>