<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6fc1d575-bbd8-42c9-ac63-fd4d8e40ba2f</elementGuidId>
    <imagePath></imagePath>
    <name>button_TestCase</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#g5_record_test_case</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'g5_record_test_case') and equals(@type,'button') and equals(@text,'Test Case')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="+ Test Case"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>g5_record_test_case</value>
        <webElementGuid>a80ceaa8-907d-4e68-9d27-493d2293e10b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Test Case</value>
        <webElementGuid>a80ceaa8-907d-4e68-9d27-493d2293e10b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>a80ceaa8-907d-4e68-9d27-493d2293e10b</webElementGuid>
    </webElementProperties>
</WebElementEntity>