<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cbbbe325-65b5-4571-99ac-5442a330f8e4</elementGuidId>
    <imagePath></imagePath>
    <name>link_files</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="page-tab__nav__nav-link\ tab-button\ \ d-flex\ align-items-center"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/team/926329/project/1161983/executions/6315/files') and equals(@text,'Files')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Files"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/926329/project/1161983/executions/6315/files</value>
        <webElementGuid>9af9f2c8-be6b-40c2-bf42-c1b3c5027a95</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Files</value>
        <webElementGuid>9af9f2c8-be6b-40c2-bf42-c1b3c5027a95</webElementGuid>
    </webElementProperties>
</WebElementEntity>