<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2b099da7-7ace-4ba8-91b9-d7366eb9ae81</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_68</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[3]/nav[1]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Create teams and manage teams.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Create teams and manage teams.</value>
        <webElementGuid>c48724c1-6f40-4bbc-9be6-9c76f4cc1773</webElementGuid>
    </webElementProperties>
</WebElementEntity>