<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e861872c-e818-47f3-b7cb-614441d90934</elementGuidId>
    <imagePath></imagePath>
    <name>div_EmptyDiv</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[2]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/div[2]/div[1]/div[17]/div[2]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(17) [class="product_info\ item"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>