<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3ca667a9-9d5f-44ce-8bec-614e115b9899</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_271</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[9]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Manage your project settings.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Manage your project settings.</value>
        <webElementGuid>00d2200f-10e5-471f-9357-ec29bda8419b</webElementGuid>
    </webElementProperties>
</WebElementEntity>