<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>98f763fa-e709-4424-893c-715c42198f71</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_81</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[25]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/BACKEND/APPPROVIDER/APPROVIDER_TNR_USECASES')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/BACKEND/APPPROVIDER/APPROVIDER_TNR_USECASES</value>
        <webElementGuid>a1982b4b-7988-41f3-b4e5-197bee856912</webElementGuid>
    </webElementProperties>
</WebElementEntity>