<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>535630c5-2ea3-4763-9db9-7d35ccd0a64a</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_145</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[6]/td[4]/div[1]/div[1]/div[1]/div[2]/span[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Report Uploader Test')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Report Uploader Test</value>
        <webElementGuid>6687295a-beb9-4e11-b1f1-0bcd3fa9a2ab</webElementGuid>
    </webElementProperties>
</WebElementEntity>