<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f141fc66-9859-4a61-ad6a-56822b54ddb8</elementGuidId>
    <imagePath></imagePath>
    <name>link_ctCloudBasedTestExecution</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/ul[2]/div[5]/div[1]/div[1]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-c4sutr"]:nth-child(6) [class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways MuiButtonBase-root MuiListItem-root MuiListItem-gutters MuiListItem-padding MuiListItem-button projectItem css-1ruwy3y"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/team/1162559/project/1294898') and equals(@text,'CTCloud-based Test Execution')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="CT Cloud-based Test Execution"i] &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/1162559/project/1294898</value>
        <webElementGuid>cf181020-bf35-48dd-b069-18cc4c5f1d71</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CT
        Cloud-based Test Execution</value>
        <webElementGuid>cf181020-bf35-48dd-b069-18cc4c5f1d71</webElementGuid>
    </webElementProperties>
</WebElementEntity>