<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cb93a1a7-6f36-4527-a05b-b7e97d6d22e8</elementGuidId>
    <imagePath></imagePath>
    <name>link_scriptRepositories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-link active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Script Repositories') and equals(@href,'/team/320312/project/434641/test-project') and equals(@text,'Script Repositories')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Script Repositories"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/320312/project/434641/test-project</value>
        <webElementGuid>494ed454-563f-482a-8c65-55ca090d1cc0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Script Repositories</value>
        <webElementGuid>494ed454-563f-482a-8c65-55ca090d1cc0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Script Repositories</value>
        <webElementGuid>494ed454-563f-482a-8c65-55ca090d1cc0</webElementGuid>
    </webElementProperties>
</WebElementEntity>