<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4c014d31-391f-4dc7-8b7c-b2f519432b9c</elementGuidId>
    <imagePath></imagePath>
    <name>div_EmptyDiv</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[1]/div[4]/div[11]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>["[class=\"shared-user-accounts\"]:nth-child(9)"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>