<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>67629952-d3c8-4fc1-b006-5d22eeca7b3e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Create teams and manage teams.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Create teams and manage teams.</value>
        <webElementGuid>5647781e-005e-438c-8e72-0689fb781f3a</webElementGuid>
    </webElementProperties>
</WebElementEntity>