<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fd705ee2-b4bf-48f0-803a-3d237e4f5c9d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_34</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Sign Out')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Sign Out</value>
        <webElementGuid>d3cf0f7e-da99-45d7-9180-9d58e27c60ee</webElementGuid>
    </webElementProperties>
</WebElementEntity>