<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>408cd9f2-b358-43e5-8dd7-52987858c6ad</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[4]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[4]/td[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Remove Machine')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Remove Machine</value>
        <webElementGuid>b77bbc88-ee3a-446e-8db2-e583a2fa57ab</webElementGuid>
    </webElementProperties>
</WebElementEntity>