<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>29b9e879-7e33-447a-9635-074111dbd405</elementGuidId>
    <imagePath></imagePath>
    <name>button_failedTestActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[5]/div[1]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${button_failedTestActions_class}"] &gt; #external-link-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'external-link-button') and equals(@title,'Go to Test Result details') and equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="${button_failedTestActions_internalRoleButtonName}"i] &gt;&gt; #external-link-button &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>external-link-button</value>
        <webElementGuid>ae04001f-9cae-471c-a966-df71595d8bea</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Go to Test Result details</value>
        <webElementGuid>ae04001f-9cae-471c-a966-df71595d8bea</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ae04001f-9cae-471c-a966-df71595d8bea</webElementGuid>
    </webElementProperties>
</WebElementEntity>