<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9dbf182e-9ea9-4873-b4a0-f7ef0df5137e</elementGuidId>
    <imagePath></imagePath>
    <name>button_scheduleTestRun</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#open-schedule-dialog</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'open-schedule-dialog') and equals(@title,'Schedule Test Run') and equals(@type,'button') and equals(@text,'Schedule Test Run')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Schedule Test Run"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>open-schedule-dialog</value>
        <webElementGuid>bec103e7-1052-4d0a-8175-a0277b214dd9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Schedule Test Run</value>
        <webElementGuid>bec103e7-1052-4d0a-8175-a0277b214dd9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Schedule Test Run</value>
        <webElementGuid>bec103e7-1052-4d0a-8175-a0277b214dd9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>bec103e7-1052-4d0a-8175-a0277b214dd9</webElementGuid>
    </webElementProperties>
</WebElementEntity>