<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f61df4c0-40d9-4742-8157-77ec099dde30</elementGuidId>
    <imagePath></imagePath>
    <name>div_WindowsChrome</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"xpath": "//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]", "css": ["#react-select-4-option-0 [class=\"text-wrap\"]"], "smart": ["internal:text=\"Windows Chrome\"i", "#react-select-4-option-0 div &gt;&gt; nth=2"], "children": [], "self": {}}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-select-4-option-0 [class="text-wrap"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Windows Chrome"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>