<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2970c691-241d-4b5d-aa9f-5881073bbbff</elementGuidId>
    <imagePath></imagePath>
    <name>div_SelectEnvironment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>[{"xpath": "//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]", "css": ["[class=\"react-select__control\\ react-select__control--is-focused\\ react-select__control--menu-is-open\\ css-1pahdxg-control\"] &gt; [class=\"react-select__value-container\\ react-select__value-container--is-multi\\ css-1hwfws3\"]"], "smart": ["#simple-tabpanel-0 div &gt;&gt; internal:has-text=/^Select environment$/ &gt;&gt; nth=1"], "children": [{"tag_name": "div", "class_name": "css-1wa3eu0-placeholder react-select__placeholder"}, {"tag_name": "div", "class_name": "css-1g6gooi"}], "self": {}}]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="react-select__control\ react-select__control--is-focused\ react-select__control--menu-is-open\ css-1pahdxg-control"] &gt; [class="react-select__value-container\ react-select__value-container--is-multi\ css-1hwfws3"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#simple-tabpanel-0 div &gt;&gt; internal:has-text=/^Select environment$/ &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>