<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2d19fb9b-e5a3-46ee-b6ab-c9e62d6fb956</elementGuidId>
    <imagePath></imagePath>
    <name>button_close2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[2]/div[3]/div[1]/div[1]/div[1]/span[1]/button[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-secondary"]:nth-child(2) &gt; svg</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Close"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>