<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3d164170-fe35-4abb-8dda-ad8ce8b67ef3</elementGuidId>
    <imagePath></imagePath>
    <name>button_scheduleTestRun</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#open-schedule-dialog</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'open-schedule-dialog') and equals(@title,'Schedule Test Run') and equals(@type,'button') and equals(@text,'Schedule Test Run')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Schedule Test Run"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>open-schedule-dialog</value>
        <webElementGuid>7c60ccfb-b803-406f-84bf-f89e1b948e91</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Schedule Test Run</value>
        <webElementGuid>7c60ccfb-b803-406f-84bf-f89e1b948e91</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Schedule Test Run</value>
        <webElementGuid>7c60ccfb-b803-406f-84bf-f89e1b948e91</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>7c60ccfb-b803-406f-84bf-f89e1b948e91</webElementGuid>
    </webElementProperties>
</WebElementEntity>