<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>755a3342-6114-4b3f-a4da-8e094f1c4363</elementGuidId>
    <imagePath></imagePath>
    <name>div_object4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="main-body"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="SchedulesSubscribed 3 TestCloud Sessions.Show detailsRunning in Organization0/30/00/0Schedule Test RunScript Repository: AllSort: Date Modified (Descending)NameReleaseScript RepositoryTest EnvironmentLast RunNext RunTest Run_1ccsp.gitMy Agent39 mins agoAug 23, 10:"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>