<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee29b920-20f6-4266-a2be-2b6569421f78</elementGuidId>
    <imagePath></imagePath>
    <name>link_TestCloud_Tunnels</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sub-navbar"] &gt; [class="nav-item"]:nth-child(5) &gt; [class="nav-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'TestCloud Tunnels') and equals(@href,'/team/1567490/project/1586175/testCloudTunnel') and equals(@text,'TestCloud Tunnels')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="TestCloud Tunnels"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/1567490/project/1586175/testCloudTunnel</value>
        <webElementGuid>f32dcaa2-afdf-4bc3-8f1d-416a47e911f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TestCloud Tunnels</value>
        <webElementGuid>f32dcaa2-afdf-4bc3-8f1d-416a47e911f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>TestCloud Tunnels</value>
        <webElementGuid>f32dcaa2-afdf-4bc3-8f1d-416a47e911f8</webElementGuid>
    </webElementProperties>
</WebElementEntity>