<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>840db900-f785-4c31-b377-767678c46242</elementGuidId>
    <imagePath></imagePath>
    <name>link_details</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="d-block\ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/team/1539672/project/1558977/executions/1') and equals(@text,'Details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Details"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/1539672/project/1558977/executions/1</value>
        <webElementGuid>0834fa7c-743a-4b72-876b-1e1de6a01d95</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Details</value>
        <webElementGuid>0834fa7c-743a-4b72-876b-1e1de6a01d95</webElementGuid>
    </webElementProperties>
</WebElementEntity>