<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9bd9b129-55e6-475a-81a5-f72783b43ce1</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_27</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[11]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'20230327_033739/Test Suites/1.1. Access and Authentication/1.1.2 Access - registrations/20230327_033741/videos/screen_recording_2_0.mov')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>20230327_033739/Test Suites/1.1. Access and Authentication/1.1.2 Access - registrations/20230327_033741/videos/screen_recording_2_0.mov</value>
        <webElementGuid>016876f6-1444-4146-8810-e6630473d58d</webElementGuid>
    </webElementProperties>
</WebElementEntity>