<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cb365682-215a-4ed3-a3c9-66a68eb1ff9b</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_41</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[9]/span[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'1 test. () , _ - valid ')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>1 test. () , _ - valid </value>
        <webElementGuid>33f847a0-0734-4dd3-ab85-7d9deb17ff61</webElementGuid>
    </webElementProperties>
</WebElementEntity>