<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1aa57a63-de37-43a3-ae22-1979d47ef982</elementGuidId>
    <imagePath></imagePath>
    <name>link_Schedules</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>["[class=\"sub-navbar\"] &gt; [class=\"nav-item\"]:nth-child(3) &gt; [class=\"nav-link\"]"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Schedules') and equals(@href,'/team/175666/project/1455693/grid') and equals(@text,'Schedules')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=link[name=\"Schedules\"i]", "#under-top-navbar &gt;&gt; internal:role=link &gt;&gt; nth=2"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/175666/project/1455693/grid</value>
        <webElementGuid>26fe9e48-a877-4be8-8587-e6e778750e9b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Schedules</value>
        <webElementGuid>26fe9e48-a877-4be8-8587-e6e778750e9b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Schedules</value>
        <webElementGuid>26fe9e48-a877-4be8-8587-e6e778750e9b</webElementGuid>
    </webElementProperties>
</WebElementEntity>