<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>94a124a2-f558-4761-9b00-7282712c3dba</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_12</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[1]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>