<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0edc73d5-2841-4643-bfc0-0455c5fd6fa2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_89</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'View usage dashboard of Katalon Studio and TestOps.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>View usage dashboard of Katalon Studio and TestOps.</value>
        <webElementGuid>8bc11548-0644-431f-95e5-d1960a387db9</webElementGuid>
    </webElementProperties>
</WebElementEntity>