<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0c424784-4333-4db0-86c3-4e53c80886ae</elementGuidId>
    <imagePath></imagePath>
    <name>link_gssItAms</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/ul[2]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiList-root\ MuiList-padding\ MuiList-subheader\ css-19o40po"]:nth-child(2) &gt; [class="MuiButtonBase-root\ MuiListItem-root\ MuiListItem-gutters\ MuiListItem-padding\ MuiListItem-button\ organizationItem\ css-dh1yhp"]:nth-child(2) [class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineAlways\ MuiTypography-root\ MuiTypography-body1\ MuiListItemText-primary\ css-5leo3l"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/organization/755790/home') and equals(@text,'GSS IT AMS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="GSS IT AMS"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/organization/755790/home</value>
        <webElementGuid>bb5ca71c-b7bd-41c3-b32e-9e0593dcdcdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>GSS IT AMS</value>
        <webElementGuid>bb5ca71c-b7bd-41c3-b32e-9e0593dcdcdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>