<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>77996d65-4f27-48d9-8984-4977b39a4670</elementGuidId>
    <imagePath></imagePath>
    <name>input_selectKatalonFiles</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/form[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(2) [multiple=""]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'file')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>form &gt;&gt; internal:has-text="Select Katalon report files"i &gt;&gt; internal:role=textbox</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>file</value>
        <webElementGuid>36ef90de-8ee8-4482-be68-0324c9296a73</webElementGuid>
    </webElementProperties>
</WebElementEntity>