<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e983f23a-9baf-49ef-b913-16ee5250405a</elementGuidId>
    <imagePath></imagePath>
    <name>link_webServices</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sub-navbar"] &gt; [class="nav-item"]:nth-child(4) &gt; [class="nav-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Web Services') and equals(@href,'/team/1572631/project/1591349/web-services') and equals(@text,'Web Services')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Web Services"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/team/1572631/project/1591349/web-services</value>
        <webElementGuid>5f797eb2-2516-45dc-ad2b-ea93fa4c95f3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Web Services</value>
        <webElementGuid>5f797eb2-2516-45dc-ad2b-ea93fa4c95f3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Web Services</value>
        <webElementGuid>5f797eb2-2516-45dc-ad2b-ea93fa4c95f3</webElementGuid>
    </webElementProperties>
</WebElementEntity>